### ISSUE TITLE
Collapsing the last subcategory tab messes up the UI width

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/VABOrganizer#11]
See video:
https://github.com/user-attachments/assets/c54ee968-e32a-4541-a47c-57d1c94dd415

**Comment by ChrisAdderley** [comment]
Fixed in https://github.com/post-kerbin-mining-corporation/VABOrganizer/commit/fb7f8736d31536e4e5e4009ab49da83b80c8d3af
