### ISSUE TITLE
Contributing Mod Compatibility Patches

### ISSUE THREAD

**Issue by Dragonking074** [post-kerbin-mining-corporation/VABOrganizer#13]
I just got this mod, just have to say its a great thing for people with huge modpacks like me. I have also noticed there aren`t really any patches for compatibility with modded parts yet so it cant actually help all that much yet. Ive looked at the cfgs for assigning parts to categories, I think I could easily make lots of those for all of my various mods. Since id do this anyways to be able to fully utilize the mod I wanted to ask if I could maybe officially contribute these to the mod. For this id also have to add some subcategories to the cfgs for those, like for example LH2 engines. Also what/if any compatibility patches like this are already in the works? Just asking so I dont make redundant cfgs.

**Comment by Rodg88** [comment]
Well Cryogenic Engines already exists, as well as a few other subcategories that aren't used by default to allow for mod compat. (a mod can reference the unused category without defining it, preventing multiple mods creating duplicate categories. Some of them may have single stock parts that may be suitable, but remain unassigned to avoid categories with single parts in them. If a mod adds more similar parts, they can then add the stock part to the now used category too.)

And BDB already has compat finished, just waiting on this to actually be released before pushing to BDB's dev branch.

**Comment by ChrisAdderley** [comment]
The idea here is for the base mod to specifically NOT hold any compatibility patches beyond stock + BG/MH, and to limit the categories to things that are as common as possible. I don't want to repeat CRP/CTT mistakes.

So if you want to ship compat, go to various mod authors and offer to do it, or make a separate standalone mod.
