### ISSUE TITLE
ReStock causes "Vector" engine to be categorized as 2.5m

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [post-kerbin-mining-corporation/VABOrganizer#18]
Based on perusing VABOrganizer's files (I know coding in general but not KSP modding), I believe that the profile sizes are computed at runtime, not stored like the categories are. So I'm _pretty sure_ this is a bug in VABOrganzier's profile-size-computing logic.

![image](https://github.com/user-attachments/assets/a4b0c4f2-7490-4cc6-aeb7-20257de8fb75)

[ckan dump](https://github.com/user-attachments/files/16667451/2024-08-19.ckan.txt)

**Comment by ChrisAdderley** [comment]
Not a VABO issue, a restock issue and has been fixed since 1.5.0
