### ISSUE TITLE
Changing category/picking a part shows all hidden parts from collapsed subcategories

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/VABOrganizer#4]
If you collapse a subcategory to hide the contents, then change to a different category and back, the parts that were hidden by the collapsed subcategory will be visible again, while the subcategory will still be in a collapsed state.

https://github.com/post-kerbin-mining-corporation/VABOrganizer/assets/2611674/5b7e91b7-5601-49ac-a31f-8910cfe60dcb

Also happens the first time you enter the VAB in a session when you pick a part, instead of having to change category. This only happens once in a game session.

https://github.com/post-kerbin-mining-corporation/VABOrganizer/assets/2611674/06431b05-68ae-45bf-9008-cb2786a0234b

**Comment by ChrisAdderley** [comment]
This has been fixed in https://github.com/post-kerbin-mining-corporation/VABOrganizer/commit/f7482559d569423224a09690b783d18a4c6a589e
