### ISSUE TITLE
labels in RnD overlap 'owned' label

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/VABOrganizer#7]
![image](https://github.com/user-attachments/assets/0955915d-4211-4252-bc15-908e15c8a7ef)

**Comment by ChrisAdderley** [comment]
Well I didn't even know they worked there! Fixed in https://github.com/post-kerbin-mining-corporation/VABOrganizer/commit/237881de17bbf154d09cba9972858ab4bd55be2e .

**Comment by Rodg88** [comment]
![image](https://github.com/user-attachments/assets/da5fde89-0165-4671-9320-531348f6e132)
Having a custom larger LabelFontSize stops the labels showing in the RND scene. I have set it to 11 here. Removing the settings patch restores the labels.

Just ignoring the LabelFontSize and using default fontsize in RND would be fine imo, the default looks good on the small RND icons, even on my 1600p monitor with 100% UI scale
