### ISSUE TITLE
Custom font size prevents RnD labels from showing

### ISSUE THREAD

**Issue by Rodg88** [post-kerbin-mining-corporation/VABOrganizer#8]
![image](https://github.com/user-attachments/assets/da5fde89-0165-4671-9320-531348f6e132)
Having a custom larger LabelFontSize stops the labels showing in the RND scene. I have set it to 11 here. Removing the settings patch restores the labels.

Just ignoring the LabelFontSize and using default fontsize in RND would be fine imo, the default looks good on the small RND icons, even on my 1600p monitor with 100% UI scale

**Comment by ChrisAdderley** [comment]
Added separate setting `RDLabelFontSize` that controls the R&D scene's labels in https://github.com/post-kerbin-mining-corporation/VABOrganizer/commit/0bcae451317f0b46da21fc58f249adc95f111490
